version: '3.9'

volumes:
    postgres-data: {}

services:
    db:
        image: groonga/pgroonga:latest-alpine-15
        env_file: ./.env.local
        restart: always
        ports:
            - "${GER_POSTGRES_PORT}:${GER_POSTGRES_PORT}"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${GER_POSTGRES_PASSWORD}
            POSTGRES_DB: ${GER_POSTGRES_DATABASE_NAME}

    backend:
        build:
            context: .
            target: dev
            dockerfile: ./Dockerfile
        env_file: ./.env.local
        depends_on:
            - db
